// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfnyksansgvaphkycpel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhmbnlrc2Fuc2d2YXBoa3ljcGVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNTk2MDYsImV4cCI6MjA2MTczNTYwNn0.D236Z9IDJ5_vrn0U9bDCVrG91ojF_GI-2YntRi9gLRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
//criar variael de ambiente para esconder client do banco de dados

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);